#!/usr/bin/env bash
# Creates the initial MAREA backlog. Review this file before executing it.
set -euo pipefail

REPO="mariaherrerosanchez/Proyecto10_MAREA_MariaHerrero"
PROJECT_NUMBER=2
PROJECT_OWNER="mariaherrerosanchez"
created=0
skipped=0

command -v gh >/dev/null 2>&1 || { echo "Error: GitHub CLI (gh) no está disponible." >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "Error: GitHub CLI no está autenticado." >&2; exit 1; }

issue_in_project() {
  local issue_url="$1"
  gh project item-list "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --limit 1000 --format json \
    --jq ".items[] | select(.content.url == \"$issue_url\") | .id" | grep -q .
}

add_issue_to_project() {
  local title="$1" issue_url="$2"
  if issue_in_project "$issue_url"; then
    echo "Ya pertenece al Project #$PROJECT_NUMBER: $title"
  else
    gh project item-add "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --url "$issue_url" >/dev/null
    echo "Añadida al Project #$PROJECT_NUMBER (estado predeterminado Backlog): $title"
  fi
}

create_issue() {
  local title="$1" epic_code="$2" epic_name="$3" epic_label="$4" milestone="$5" priority="$6" role="$7" goal="$8" value="$9" criteria="${10}" dependencies="${11:-}"
  local issue_id existing_issue existing_title issue_url body information
  issue_id="${title%% — *}"
  existing_issue="$(gh issue list --repo "$REPO" --state all --search "$issue_id in:title" --limit 1000 --json title,url --jq ".[] | select(.title | startswith(\"$issue_id —\")) | [.title, .url] | @tsv")"
  if [[ -n "$existing_issue" ]]; then
    IFS=$'\t' read -r existing_title issue_url <<< "$existing_issue"
    if [[ "$existing_title" == "$title" ]]; then
      echo "Omitida (ya existe): $title"
    else
      echo "Omitida (US existente con título pendiente de sincronizar): $existing_title"
    fi
    add_issue_to_project "$title" "$issue_url"
    ((skipped+=1))
    return
  fi
  information=$'- Épica: '"$epic_code"$' — '"$epic_name"$'\n- Milestone: '"$milestone"$'\n- Prioridad: '"$priority"
  if [[ -n "$dependencies" ]]; then
    information+=$'\n- Dependencias: '"$dependencies"
  fi
  body=$(cat <<EOF
## Historia de usuario

Como $role,
quiero $goal,
para $value.

## Criterios de aceptación

$criteria

## Información

$information
EOF
)
  issue_url="$(gh issue create --repo "$REPO" --title "$title" --body "$body" --milestone "$milestone" --label "$epic_label" --label "priority:$priority")"
  echo "Creada: $title"
  add_issue_to_project "$title" "$issue_url"
  ((created+=1))
}

# EP01 — Fundación | M1 — 🌱 MAREA nace | P0
create_issue "US-001 — Inicializar estructura profesional del repositorio" "EP01" "Fundación" "epic:foundation" "M1 — 🌱 MAREA nace" "P0" "desarrolladora del proyecto" "inicializar una estructura de repositorio clara" "disponer de una base mantenible para MAREA" $'- El repositorio separa la documentación, scripts y futuras capas de aplicación.\n- Existe una convención documentada para nombres y ubicación de archivos.\n- La estructura no incluye todavía código de frontend ni backend.\n- Los archivos de configuración inicial son coherentes con la estructura.'
create_issue "US-002 — Configurar backend FastAPI" "EP01" "Fundación" "epic:foundation" "M1 — 🌱 MAREA nace" "P0" "desarrolladora" "configurar la base del backend FastAPI" "exponer una API preparada para los flujos de MAREA" $'- El servicio FastAPI puede iniciarse en entorno local.\n- Se define un punto de comprobación de salud de la API.\n- La configuración del servicio se obtiene de variables de entorno.\n- La API permite configurar orígenes permitidos para el frontend.'
create_issue "US-003 — Configurar frontend React + TypeScript" "EP01" "Fundación" "epic:foundation" "M1 — 🌱 MAREA nace" "P0" "desarrolladora" "configurar el frontend con React y TypeScript" "contar con una interfaz mantenible y tipada" $'- El proyecto usa React y TypeScript.\n- El arranque local está documentado.\n- La configuración no contiene claves ni secretos.\n- La estructura admite las pantallas previstas de MAREA.'
create_issue "US-004 — Establecer comunicación frontend-backend" "EP01" "Fundación" "epic:foundation" "M1 — 🌱 MAREA nace" "P0" "persona usuaria" "que la interfaz se comunique con la API" "usar los flujos de generación desde una única experiencia" $'- El frontend consulta un endpoint de comprobación del backend.\n- La URL de la API se configura por variable de entorno.\n- Se informa de un error de conexión sin exponer detalles internos.\n- La comunicación respeta la configuración CORS del backend.'

# EP02 — Experiencia de usuario | M1 — 🌱 MAREA nace | P0
create_issue "US-005 — Crear layout, navegación y design system responsive" "EP02" "Experiencia de usuario" "epic:ux" "M1 — 🌱 MAREA nace" "P0" "persona creadora" "navegar por una interfaz coherente y adaptable" "acceder con claridad a las áreas de MAREA" $'- La navegación incluye Inicio, Crear, Radar, Biblioteca, Ciencia, Perfiles y Configuración.\n- El layout se adapta a pantalla pequeña y grande.\n- Los componentes visuales comparten tipografía, espaciado y estados consistentes.\n- La identidad visual comunica movimiento, creación, expansión y comunicación.\n- La interfaz evita una apariencia genérica de producto de IA.'

# EP17 — Entrega | M1 / M8
create_issue "US-006 — Configurar secretos y variables de entorno" "EP17" "Entrega" "epic:delivery" "M1 — 🌱 MAREA nace" "P0" "desarrolladora" "configurar variables de entorno de forma segura" "cambiar proveedores y entornos sin versionar secretos" $'- Existe un archivo .env.example sin secretos reales.\n- Las claves de Groq, OpenRouter y LangSmith se leen desde el entorno.\n- La configuración de Ollama, base de datos y frontend puede ajustarse por variables.\n- Los archivos .env están ignorados por Git y .env.example no lo está.'

# EP03 — LLM | M2 / M4
create_issue "US-007 — Integrar LangChain y abstracción de proveedores LLM" "EP03" "LLM" "epic:llm" "M2 — ✨ Primera ola" "P0" "desarrolladora" "usar una abstracción común de proveedores LLM" "cambiar entre modelos sin reescribir el flujo de contenido" $'- La capa de generación depende de una interfaz de proveedor definida.\n- LangChain orquesta la llamada al modelo seleccionado.\n- La configuración identifica proveedor y modelo usados.\n- Un fallo de proveedor produce un error controlado y trazable.'
create_issue "US-008 — Integrar primer LLM gratuito" "EP03" "LLM" "epic:llm" "M2 — ✨ Primera ola" "P0" "persona creadora" "generar contenido con un primer modelo accesible" "probar el flujo esencial sin contratar servicios de pago" $'- Se puede seleccionar un modelo gratuito o local configurado.\n- Una solicitud válida devuelve texto generado.\n- La respuesta identifica el proveedor y modelo usados.\n- Un proveedor no configurado no impide mostrar una explicación útil.'
create_issue "US-009 — Implementar sistema estructurado de prompts" "EP03" "LLM" "epic:llm" "M2 — ✨ Primera ola" "P0" "persona creadora" "aportar contexto estructurado a la generación" "obtener resultados alineados con mi objetivo, nichos y audiencia" $'- El prompt incorpora tema, cero, uno o varios nichos, subnicho o especialización opcional, objetivo, audiencia, tono, idioma y contexto adicional.\n- Los nichos de la solicitud se representan como ámbitos combinables sin imponer una jerarquía.\n- La ausencia de nichos no bloquea la generación ni produce texto artificial.\n- El prompt recibe la plataforma solicitada como dato diferenciado.\n- Las instrucciones, nichos y competencias del perfil pueden añadirse sin modificar el código del prompt base.\n- Los nichos de solicitud, los nichos de perfil y la audiencia se conservan como contextos diferenciados.\n- El contexto adicional permanece independiente de nichos y subnicho.\n- La configuración usada, incluida la versión de prompt, queda disponible para trazabilidad.\n- La resolución de preferencias de cuenta pertenece a US-020 y US-045; esta historia admite contexto ya resuelto.' "US-007, US-008"

# EP04 — Contenido | M2 / M3
create_issue "US-010 — Crear formulario de generación de contenido" "EP04" "Contenido" "epic:content" "M2 — ✨ Primera ola" "P0" "persona creadora" "introducir los datos de una idea" "solicitar contenido adaptado de forma guiada" $'- El formulario solicita tema o idea, objetivo, audiencia, tono, idioma y contexto adicional.\n- Permite cero, uno o varios nichos; los nichos son recomendados, no obligatorios.\n- Ofrece nichos sugeridos estáticos, permite activar o desactivar varios y añadir nichos personalizados sin duplicados.\n- Permite eliminar individualmente nichos seleccionados.\n- El subnicho o especialización adicional es opcional e independiente de que existan nichos.\n- Los campos obligatorios se validan sin requerir nichos ni subnicho.\n- Explica visualmente que los nichos son ámbitos combinables y que la audiencia define para quién se crea el contenido.\n- Permite elegir una o varias plataformas objetivo y definir una plataforma principal para el borrador actual.\n- Conserva la selección completa de plataformas sin afirmar que ya se han generado piezas para todas.\n- Muestra estados de carga, éxito y error recuperable.\n- La integración de preferencias de cuenta como defaults editables pertenece a US-045.' "US-004, US-007, US-008, US-009"
create_issue "US-048 — Presentar el borrador de forma fiable y transparente" "EP04" "Contenido" "epic:content" "M2 — ✨ Primera ola" "P0" "persona creadora" "visualizar un borrador fiel y comprensible junto con información clara sobre su procesamiento" "revisarlo con criterio antes de utilizarlo" $'- El borrador se presenta de forma legible y fiel al contenido generado.\n- Se resuelven Markdown escapado, caracteres escapados y entidades HTML visibles cuando no correspondan.\n- La normalización no elimina ni transforma silenciosamente contenido legítimo del modelo.\n- La interfaz conserva revisión humana explícita antes de cualquier acción de salida.\n- Se muestran el proveedor y modelo efectivos.\n- Se indica si el procesamiento efectivo es LOCAL o EXTERNO mediante metadatos explícitos del proveedor.\n- No se exponen secretos, claves, mensajes internos ni datos sensibles.\n- Los estados de carga, éxito y error recuperable se presentan de forma segura.\n- Un error visual no hace perder el texto ya generado cuando esté disponible.' "US-007, US-008, US-009, US-010"
create_issue "US-011 — Generar contenido específico para LinkedIn" "EP04" "Contenido" "epic:content" "M2 — ✨ Primera ola" "P0" "persona creadora" "obtener una propuesta para LinkedIn" "comunicar la idea según las características de ese canal" $'- La generación recibe LinkedIn como plataforma objetivo diferenciada.\n- La adaptación de LinkedIn se mantiene separada del proveedor LLM, la presentación y la futura persistencia.\n- El contexto admite cero, uno o varios nichos, subnicho o especialización, audiencia, tono, idioma y contexto adicional.\n- La generación aplica los guardrails mínimos de US-038 y no inventa información factual no respaldada.\n- El resultado es una pieza transitoria revisable; no se persiste hasta US-021 y US-022.\n- La configuración permanece disponible en la traza temporal.\n- El flujo conserva revisión humana antes de cualquier acción de salida.\n- Añade casos específicos de LinkedIn al evaluation harness compartido; no crea un sistema de evaluación independiente.' "US-007, US-008, US-009, US-010, US-038, US-048"
create_issue "US-012 — Generar contenido específico para Instagram" "EP04" "Contenido" "epic:content" "M2 — ✨ Primera ola" "P0" "persona creadora" "obtener una propuesta para Instagram" "comunicar la idea según las características de ese canal" $'- La generación recibe Instagram como plataforma objetivo diferenciada.\n- La adaptación de Instagram se mantiene separada del proveedor LLM, la presentación y la futura persistencia.\n- El contexto admite cero, uno o varios nichos, subnicho o especialización, audiencia, tono, idioma y contexto adicional.\n- La generación aplica los guardrails mínimos de US-038 y no inventa información factual no respaldada.\n- El resultado es una pieza transitoria revisable; no se persiste hasta US-021 y US-022.\n- La configuración permanece disponible en la traza temporal.\n- El flujo conserva revisión humana antes de cualquier acción de salida.\n- Añade casos específicos de Instagram al evaluation harness compartido; no crea un sistema de evaluación independiente.' "US-007, US-008, US-009, US-010, US-038, US-048"
create_issue "US-013 — Generar contenido específico para Facebook" "EP04" "Contenido" "epic:content" "M2 — ✨ Primera ola" "P0" "persona creadora" "obtener una propuesta para Facebook" "comunicar la idea según las características de ese canal" $'- La generación recibe Facebook como plataforma objetivo diferenciada.\n- La adaptación de Facebook se mantiene separada del proveedor LLM, la presentación y la futura persistencia.\n- El contexto admite cero, uno o varios nichos, subnicho o especialización, audiencia, tono, idioma y contexto adicional.\n- La generación aplica los guardrails mínimos de US-038 y no inventa información factual no respaldada.\n- El resultado es una pieza transitoria revisable; no se persiste hasta US-021 y US-022.\n- La configuración permanece disponible en la traza temporal.\n- El flujo conserva revisión humana antes de cualquier acción de salida.\n- Añade casos específicos de Facebook al evaluation harness compartido; no crea un sistema de evaluación independiente.' "US-007, US-008, US-009, US-010, US-038, US-048"
create_issue "US-014 — Generar contenido específico para Blog" "EP04" "Contenido" "epic:content" "M2 — ✨ Primera ola" "P0" "persona creadora" "obtener una propuesta para Blog" "comunicar la idea según las características de ese canal" $'- La generación recibe Blog como plataforma objetivo diferenciada.\n- La adaptación de Blog se mantiene separada del proveedor LLM, la presentación y la futura persistencia.\n- El contexto admite cero, uno o varios nichos, subnicho o especialización, audiencia, tono, idioma y contexto adicional.\n- La generación aplica los guardrails mínimos de US-038 y no inventa información factual no respaldada.\n- El resultado es una pieza transitoria revisable; no se persiste hasta US-021 y US-022.\n- La configuración permanece disponible en la traza temporal.\n- El flujo conserva revisión humana antes de cualquier acción de salida.\n- Añade casos específicos de Blog al evaluation harness compartido; no crea un sistema de evaluación independiente.' "US-007, US-008, US-009, US-010, US-038, US-048"
create_issue "US-015 — Seleccionar múltiples plataformas simultáneamente" "EP04" "Contenido" "epic:content" "M3 — 🌊 Multicanal real" "P0" "persona creadora" "seleccionar una, varias o todas las plataformas" "crear una campaña multicanal desde una misma idea" $'- Se puede elegir una única plataforma.\n- Se pueden elegir varias plataformas simultáneamente.\n- Existe una acción para seleccionar todas las plataformas disponibles.\n- Cada plataforma seleccionada genera una pieza independiente.\n- La selección se conserva durante la solicitud.'
create_issue "US-016 — Revisar y editar cada contenido generado" "EP04" "Contenido" "epic:content" "M3 — 🌊 Multicanal real" "P0" "persona creadora" "revisar y editar cada pieza antes de usarla" "mantener el control editorial del contenido" $'- Cada resultado se muestra antes de cualquier acción de salida.\n- El texto de cada plataforma se puede editar.\n- La edición de una pieza no modifica las demás.\n- Se puede seleccionar una pieza revisada para conservarla.\n- No existe publicación automática después de generar.'
create_issue "US-017 — Regenerar independientemente una plataforma" "EP04" "Contenido" "epic:content" "M3 — 🌊 Multicanal real" "P0" "persona creadora" "regenerar solo una pieza de plataforma" "mejorar un resultado sin perder los demás" $'- La acción de regeneración se inicia desde una pieza concreta.\n- La nueva generación conserva el contexto de la solicitud original.\n- Las piezas de otras plataformas no se modifican.\n- La versión anterior solo se conserva o distingue de forma persistente cuando existan US-021 y US-022.' "US-015, US-016; historial persistente: US-021 y US-022"

# EP08 — Publicación y salida | M3 / M5
create_issue "US-018 — Copiar y descargar contenido generado" "EP08" "Publicación y salida" "epic:publishing" "M3 — 🌊 Multicanal real" "P0" "persona creadora" "copiar o descargar una pieza revisada" "utilizarla aunque no haya integración social" $'- Cada pieza permite copiar su texto al portapapeles.\n- Cada pieza permite descargarse en un formato de texto.\n- Copiar o descargar no publica contenido en ninguna red.\n- La acción confirma éxito o informa de fallo recuperable.'
create_issue "US-027 — Exportar un paquete multicanal de contenido" "EP08" "Publicación y salida" "epic:publishing" "M5 — 🎨 Contenido completo" "P1" "persona creadora" "exportar un conjunto de piezas multicanal" "reutilizar una campaña completa fuera de MAREA" $'- La exportación incluye las piezas seleccionadas y su plataforma.\n- El paquete distingue claramente cada contenido.\n- Se pueden excluir piezas no aprobadas.\n- La exportación no requiere conectar cuentas sociales.'
create_issue "US-028 — Preparar arquitectura segura para publicación social" "EP08" "Publicación y salida" "epic:publishing" "M5 — 🎨 Contenido completo" "P1" "desarrolladora" "preparar conectores de publicación desacoplados" "poder integrar redes sociales en el futuro sin alterar la generación" $'- La publicación se define mediante una abstracción de conector.\n- Ningún conector publica sin una acción explícita posterior a la revisión.\n- La ausencia de conectores mantiene disponibles copia y descarga.\n- Las credenciales de conectores se obtienen desde variables de entorno.'

# EP05 — Perfiles | M4
create_issue "US-019 — Crear y gestionar perfiles de creador/marca" "EP05" "Perfiles" "epic:profiles" "M4 — 👤 Tu voz, no la de la IA" "P1" "persona creadora" "crear y gestionar perfiles configurables" "adaptar MAREA a personas, marcas, empresas o proyectos" $'- Se pueden crear perfiles de persona, marca, empresa o proyecto.\n- Un perfil admite nombre, descripción y profesión o sector.\n- Un perfil admite experiencia, conocimientos y competencias.\n- Un perfil permite asociar uno o varios nichos, subnichos opcionales y temas permitidos o evitados.\n- Un perfil admite audiencia, objetivos, tono, estilo y plataformas habituales.\n- Identidad, voz, conocimiento o hechos, preferencias, plataformas y fuentes se mantienen como conceptos diferenciados; las fuentes verificadas se gestionan en US-049.\n- Cada perfil pertenece a la cuenta activa; la propiedad y el aislamiento entre cuentas se resuelven en US-047.\n- Se pueden actualizar y consultar perfiles existentes.'
create_issue "US-020 — Aplicar voz, competencias y preferencias del perfil" "EP05" "Perfiles" "epic:profiles" "M4 — 👤 Tu voz, no la de la IA" "P1" "persona creadora" "aplicar mi perfil a una generación" "obtener contenido acorde a mi voz y contexto" $'- La generación puede asociarse a un perfil elegido.\n- El contexto incluye nichos, subnichos, tono, estilo, audiencia y objetivos del perfil.\n- Se incluyen conocimientos, competencias, temas principales y temas a evitar.\n- Nichos y audiencia se aplican como datos distintos.\n- Se aplican instrucciones personalizadas e información de marca cuando existan.\n- Solo se aplica contexto autorizado y trazable; las fuentes verificadas se gestionan en US-049.\n- El perfil seleccionado prevalece sobre las preferencias de cuenta, sin sustituir los datos explícitos de la solicitud según US-045.\n- El perfil aplicado queda registrado con la generación.'
create_issue "US-049 — Gestionar fuentes verificadas de contexto por perfil" "EP05" "Perfiles" "epic:profiles" "M4 — 👤 Tu voz, no la de la IA" "P1" "persona creadora" "gestionar fuentes verificadas de contexto para un perfil" "aportar información autorizada sin convertir el perfil en una copia de datos externos" $'- Se pueden registrar información manual, documentos aportados por la persona usuaria, CV como posible tipo de fuente, publicaciones anteriores autorizadas e información o documentación de negocio.\n- Cada fuente conserva procedencia, permiso o autorización y la relación con el perfil correspondiente.\n- Identidad, voz, conocimiento o hechos, preferencias, plataformas y fuentes se mantienen diferenciados.\n- Solo se envía al LLM el contexto mínimo necesario para la solicitud.\n- No se asume scraping de LinkedIn, Instagram, Facebook ni otras redes.\n- Las fuentes pueden emplearse como contexto verificable sin sustituir la revisión humana.' "US-019, US-021, US-043, US-047"

# EP06 — Biblioteca | M4
create_issue "US-021 — Implementar SQLite + SQLAlchemy" "EP06" "Biblioteca y persistencia" "epic:library" "M4 — 👤 Tu voz, no la de la IA" "P1" "desarrolladora" "persistir los datos de MAREA con SQLite y SQLAlchemy" "conservar información sin depender de un servicio de pago" $'- La aplicación usa SQLite como base de datos local.\n- SQLAlchemy gestiona el acceso a datos.\n- Se persisten cuentas, preferencias de cuenta, perfiles, configuraciones, generaciones y contenidos.\n- El esquema admite las relaciones de propiedad entre cuenta, perfiles, generaciones y contenidos requeridas por US-047.\n- Los perfiles persisten uno o varios nichos y sus subnichos opcionales.\n- El esquema permite asociar fuentes verificadas y su procedencia a perfiles cuando se implemente US-049.\n- La ubicación de la base de datos se configura por entorno.'
create_issue "US-022 — Guardar y consultar biblioteca/historial" "EP06" "Biblioteca y persistencia" "epic:library" "M4 — 👤 Tu voz, no la de la IA" "P1" "persona creadora" "guardar y consultar mis generaciones" "recuperar contenido y contexto previamente creados" $'- Una generación puede guardarse con sus piezas por plataforma.\n- La biblioteca muestra contenido y plataforma asociados a la cuenta activa según la propiedad definida en US-047.\n- Se puede consultar la configuración, incluidos nichos, subnicho o especialización, contexto adicional y perfil usados.\n- La trazabilidad conserva proveedor, modelo, versión de prompt y fuentes cuando correspondan.\n- Un contenido puede marcarse como descartado sin eliminar la trazabilidad necesaria.'

# EP16 — Cuenta y personalización | M4
create_issue "US-043 — Registrar e iniciar sesión en una cuenta" "EP16" "Cuenta y personalización" "epic:account-personalization" "M4 — 👤 Tu voz, no la de la IA" "P1" "persona usuaria" "crear una cuenta e iniciar sesión" "acceder de forma identificada a mis datos y preferencias" $'- Se puede crear una cuenta e iniciar sesión con credenciales válidas.\n- La validación de acceso informa errores controlados sin exponer datos sensibles.\n- Tras autenticarme, la identidad de la cuenta queda disponible durante la sesión.\n- La cuenta persistente se diferencia de cualquier perfil de creador, marca, empresa o proyecto.\n- No se incluyen todavía recuperación de contraseña, verificación de email, OAuth, proveedores externos, roles ni administración.'
create_issue "US-044 — Gestionar sesión, cierre e identidad de cuenta" "EP16" "Cuenta y personalización" "epic:account-personalization" "M4 — 👤 Tu voz, no la de la IA" "P1" "persona usuaria" "gestionar mi sesión e identidad de cuenta" "mantener el control sobre el acceso y mi representación básica" $'- Una sesión válida puede restaurarse al volver a la aplicación.\n- Existe una acción explícita para cerrar sesión.\n- Se puede consultar cuál es la cuenta activa.\n- Se puede actualizar la identidad básica de la cuenta, incluido nombre y representación visual mínima.\n- Cuenta y Perfil se presentan y persisten como conceptos distintos.'
create_issue "US-045 — Configurar preferencias personales de creación" "EP16" "Cuenta y personalización" "epic:account-personalization" "M4 — 👤 Tu voz, no la de la IA" "P1" "persona usuaria" "configurar mis preferencias personales de creación" "partir de valores relevantes sin perder control sobre cada solicitud" $'- Se pueden configurar y modificar sector o ámbito profesional, intereses y temáticas.\n- Se pueden configurar plataformas preferidas y preferencias predeterminadas de generación.\n- Las preferencias de cuenta se persisten y se recuperan para la cuenta activa.\n- La precedencia del contexto es: solicitud actual > perfil seleccionado > preferencias de cuenta.\n- Las preferencias de cuenta funcionan como defaults editables y nunca impiden una sobrescritura consciente.\n- Cuando exista el formulario, sus preferencias se proponen como valores editables sin sustituir datos explícitos de la solicitud.'
create_issue "US-046 — Personalizar Radar con preferencias de cuenta" "EP16" "Cuenta y personalización" "epic:account-personalization" "M6 — 🌊 En la ola" "P2" "persona usuaria" "usar mis preferencias de cuenta en el Radar" "recibir oportunidades relevantes aun cuando no elija un perfil o nicho concreto" $'- El Radar puede usar sector, intereses, temáticas y plataformas preferidas de la cuenta como contexto predeterminado cuando corresponda.\n- Las preferencias de cuenta actúan como fallback cuando no existe un perfil, nicho o contexto más específico seleccionado.\n- US-030 mantiene el filtrado explícito basado en perfil, nicho y competencias reales.\n- La personalización no altera las reglas de inspiración, originalidad ni prohibición de copiar publicaciones de terceros.'
create_issue "US-047 — Asociar perfiles, contenidos, biblioteca e historial a la cuenta" "EP16" "Cuenta y personalización" "epic:account-personalization" "M4 — 👤 Tu voz, no la de la IA" "P1" "persona usuaria" "asociar mis datos de MAREA a mi cuenta" "consultar únicamente mis perfiles y contenidos sin perder trazabilidad" $'- Los perfiles pertenecen a una cuenta.\n- Las generaciones y sus piezas pertenecen a una cuenta.\n- Biblioteca e historial se asocian a la cuenta activa.\n- Las consultas se limitan a la cuenta activa y aíslan los datos entre cuentas.\n- La asociación conserva la trazabilidad existente de configuraciones, fuentes y resultados.'
create_issue "US-050 — Gestionar retención y eliminación de datos propios" "EP16" "Cuenta y personalización" "epic:account-personalization" "M4 — 👤 Tu voz, no la de la IA" "P1" "persona usuaria" "conocer, retener o eliminar mis datos propios" "mantener control sobre mi información con privacidad por diseño" $'- Se identifica qué datos se persisten para la cuenta activa y su finalidad.\n- Se pueden eliminar contenidos de Biblioteca e historial propios.\n- Se pueden eliminar perfiles y fuentes propias cuando existan.\n- Tras eliminar contenido, deja de mostrarse, reutilizarse y enviarse a proveedores como contexto.\n- Se explica el comportamiento de la trazabilidad tras cada eliminación.\n- La retención de generaciones, piezas, perfiles, fuentes, configuraciones y metadatos queda documentada y limitada a lo necesario.\n- La eliminación respeta el aislamiento entre cuentas y la privacidad por diseño.' "US-021, US-022, US-043, US-047"

# EP03 — LLM | M4
create_issue "US-023 — Integrar un segundo proveedor/modelo LLM" "EP03" "LLM" "epic:llm" "M4 — 👤 Tu voz, no la de la IA" "P1" "desarrolladora" "integrar un segundo proveedor o modelo LLM" "disponer de alternativa ante límites o fallos del proveedor inicial" $'- El segundo proveedor se configura de forma independiente.\n- La abstracción existente permite seleccionarlo sin duplicar el flujo.\n- La trazabilidad identifica el proveedor y modelo efectivos.\n- Un fallo del proveedor seleccionado se comunica de forma controlada.'
create_issue "US-024 — Integrar ejecución local mediante Ollama" "EP03" "LLM" "epic:llm" "M4 — 👤 Tu voz, no la de la IA" "P1" "persona creadora" "usar un modelo local mediante Ollama" "generar contenido sin depender de un servicio de pago" $'- La URL y el modelo de Ollama son configurables.\n- Ollama puede seleccionarse como proveedor de generación.\n- La aplicación informa claramente si el servicio local no está disponible.\n- La interfaz distingue el procesamiento local y muestra proveedor y modelo efectivos.\n- Las generaciones con Ollama registran proveedor y modelo.'

# EP07 — Imágenes | M5
create_issue "US-025 — Generar imágenes mediante proveedor gratuito/local" "EP07" "Imágenes" "epic:images" "M5 — 🎨 Contenido completo" "P1" "persona creadora" "generar imágenes mediante un proveedor desacoplado" "acompañar el contenido sin bloquear el flujo textual" $'- La integración usa una abstracción ImageProvider.\n- Se prioriza un proveedor gratuito o local.\n- La indisponibilidad del proveedor no impide generar ni gestionar texto.\n- Texto e imagen mantienen estados y errores independientes, con posibilidad de continuar sin imagen.\n- Se registra el proveedor usado cuando la imagen se genera.'
create_issue "US-026 — Asociar, visualizar y descargar imágenes" "EP07" "Imágenes" "epic:images" "M5 — 🎨 Contenido completo" "P1" "persona creadora" "asociar imágenes a mis piezas" "preparar contenido multicanal completo" $'- Una imagen puede asociarse a una pieza de contenido.\n- La interfaz permite visualizar la imagen asociada.\n- La imagen puede descargarse cuando exista.\n- La ausencia de imagen no impide guardar ni exportar el contenido textual.'

# EP09 — Radar | M6
create_issue "US-029 — Obtener tendencias desde fuentes externas actuales" "EP09" "Radar" "epic:radar" "M6 — 🌊 En la ola" "P2" "persona creadora" "consultar tendencias desde fuentes externas actuales" "encontrar puntos de partida para contenido" $'- El Radar consulta fuentes externas configuradas y legítimas.\n- Cada tendencia conserva la fuente y fecha de consulta cuando estén disponibles.\n- Los errores de fuente se muestran sin detener el resto de MAREA.\n- El resultado distingue datos de tendencia de contenido generado.\n- No se basa en scraping no autorizado de redes sociales.'
create_issue "US-030 — Filtrar tendencias según nichos, perfil y competencias" "EP09" "Radar" "epic:radar" "M6 — 🌊 En la ola" "P2" "persona creadora" "filtrar tendencias con mis nichos y perfil" "priorizar oportunidades relevantes para mis competencias reales y audiencia" $'- El Radar permite seleccionar un perfil y cero, uno o varios de sus nichos, junto con una especialización opcional.\n- El filtrado considera conocimientos y competencias reales del perfil.\n- El filtrado considera nichos, subnicho o especialización, audiencia, objetivos y temas a evitar cuando existan.\n- Cuando no exista contexto más específico, puede usar el fallback de preferencias de cuenta definido en US-046 sin sustituir la selección explícita.\n- No recomienda contenido que requiera aparentar conocimientos o experiencia inexistentes.\n- Se indica qué perfil, nichos y contexto se utilizaron para el resultado.'
create_issue "US-031 — Convertir tendencias en propuestas originales de contenido" "EP09" "Radar" "epic:radar" "M6 — 🌊 En la ola" "P2" "persona creadora" "convertir una tendencia en una propuesta original" "inspirarme sin copiar publicaciones de terceros" $'- La tendencia se usa como contexto, no como texto a parafrasear.\n- La propuesta incorpora el perfil, nichos, especialización y plataforma seleccionados cuando existan.\n- La propuesta es compatible con las competencias reales y audiencia del perfil.\n- El resultado identifica la tendencia o fuente que lo inspiró.\n- La tendencia puede enviarse a Crear como contexto, sin reutilizar contenido de terceros.\n- La propuesta entra en el mismo flujo de revisión humana que una idea propia.'

# EP10 — Idiomas | M7
create_issue "US-032 — Generar contenido en ES/EN/FR/IT" "EP10" "Internacionalización" "epic:i18n" "M7 — 🔬 MAREA sabe investigar" "P2" "persona creadora" "elegir el idioma de generación" "comunicarme con audiencias en castellano, inglés, francés e italiano" $'- El formulario permite castellano, inglés, francés e italiano.\n- El idioma seleccionado se incorpora a la generación.\n- El resultado guarda el idioma usado.\n- Cada pieza multicanal puede generarse con el idioma seleccionado.'

# EP11 — RAG científico | M7
create_issue "US-033 — Construir RAG científico con arXiv y Chroma" "EP11" "RAG científico" "epic:rag" "M7 — 🔬 MAREA sabe investigar" "P2" "desarrolladora" "construir un flujo RAG científico" "recuperar contexto de arXiv para divulgación de IA y ML" $'- El flujo obtiene documentos de arXiv.\n- Los documentos se procesan y dividen en chunks.\n- Los embeddings se almacenan en Chroma.\n- Un retriever recupera chunks relevantes para la consulta.\n- El alcance inicial se centra en IA y machine learning.'
create_issue "US-034 — Generar divulgación científica con fuentes trazables" "EP11" "RAG científico" "epic:rag" "M7 — 🔬 MAREA sabe investigar" "P2" "persona creadora" "generar divulgación científica apoyada en fuentes" "explicar temas de IA y ML con respaldo identificable" $'- El modo científico usa contexto recuperado por el RAG.\n- La salida incluye las fuentes de arXiv utilizadas.\n- Las fuentes se conservan con la generación.\n- El contenido pasa por revisión humana antes de copiarse o descargarse.'

# EP12 — Finanzas | M7
create_issue "US-035 — Generar contenido financiero con información actualizada" "EP12" "Finanzas" "epic:finance" "M7 — 🔬 MAREA sabe investigar" "P2" "persona creadora" "usar información financiera externa actualizada" "generar contenido con contexto de mercado vigente" $'- La información procede de una fuente o API externa configurada.\n- Se conserva la fuente y fecha de consulta disponibles.\n- El LLM recibe los datos obtenidos como contexto diferenciado.\n- Un fallo de la fuente evita presentar datos desactualizados como actuales.'

# EP13 — Observabilidad | M2 (stretch)
create_issue "US-036 — Integrar observabilidad, trazabilidad y evaluación opcionales con LangSmith" "EP13" "Observabilidad" "epic:observability" "M2 — ✨ Primera ola" "P1" "desarrolladora" "integrar observabilidad, trazabilidad y evaluación opcionales con LangSmith" "analizar el comportamiento del flujo sin convertir el servicio externo en un requisito de MAREA" $'- LangSmith se configura de forma explícita y permanece desactivado por defecto.\n- Cuando esté habilitado, permite consultar trazas, datasets, experimentos, evaluaciones y comparativas de resultados.\n- La aplicación y el evaluation harness local siguen funcionando si LangSmith está desactivado, no está configurado o falla.\n- Se minimizan los datos enviados y no se incluyen secretos, documentación personal ni contenido sensible sin consentimiento explícito.\n- Los errores de observabilidad se manejan de forma segura y no bloquean la generación.\n- LangSmith complementa, pero no sustituye, los tests de software ni el harness reproducible de US-038.' "US-006, US-007, US-009, US-038"

# EP17 — Entrega | M8
create_issue "US-037 — Dockerizar y validar la ejecución completa de MAREA" "EP17" "Entrega" "epic:delivery" "M8 — 🚀 MAREA lista para navegar" "P1" "desarrolladora" "dockerizar y validar el flujo completo" "facilitar una ejecución reproducible de MAREA" $'- Docker Compose define los servicios necesarios para el flujo implementado.\n- La configuración sensible se proporciona por entorno y no se integra en la imagen.\n- La documentación explica cómo iniciar el entorno.\n- Se valida el flujo disponible de extremo a extremo en el entorno documentado.'

# EP14 — Calidad | M2
create_issue "US-038 — Incorporar guardrails y evaluation harness reproducible" "EP14" "Calidad" "epic:quality" "M2 — ✨ Primera ola" "P0" "desarrolladora" "incorporar guardrails y un evaluation harness reproducible" "evitar afirmaciones personales infundadas y evaluar la calidad de forma controlada" $'- No inventa experiencia profesional, cargos, empresas, estudios, herramientas o tecnologías que la persona no haya proporcionado.\n- No inventa métricas, resultados, logros, certificaciones ni testimonios.\n- No presenta como hechos afirmaciones que no estén respaldadas por el contexto disponible.\n- Permite contenido creativo cuando corresponda, diferenciándolo de hechos sobre la persona o negocio.\n- Un resultado señalado queda identificado para revisión humana.\n- Existe un dataset de evaluación versionado, sin datos personales de producción, y un harness local reproducible.\n- El harness registra de forma estructurada caso, proveedor, modelo, versión de prompt, salida, resultado y motivo de evaluación.\n- Incluye evaluaciones básicas de factualidad, cobertura de contexto, respeto de restricciones y señalización de guardrails.\n- Permite comparar resultados de prompt o modelo sin sustituir los tests de software.\n- Las llamadas a proveedores reales para evaluación son explícitamente opt-in.\n- LangSmith no es requisito para esta primera versión y no se fijan métricas objetivo antes de disponer de una línea base.\n- Los logs y resultados minimizan datos y no exponen secretos.' "US-007, US-008, US-009, US-010"

# EP15 — Agentes | M8
create_issue "US-039 — Implementar arquitectura multiagente" "EP15" "Agentes" "epic:agents" "M8 — 🚀 MAREA lista para navegar" "P3" "desarrolladora" "implementar una arquitectura multiagente" "especializar tareas y enrutar solicitudes complejas" $'- Se define un router de tareas.\n- Los agentes especializados tienen responsabilidades delimitadas.\n- El flujo conserva trazabilidad de la intervención de agentes.\n- La arquitectura no sustituye la revisión humana previa a cualquier publicación.'

# EP18 — Portfolio | M8
create_issue "US-040 — Preparar README y presentación de portfolio" "EP18" "Portfolio" "epic:portfolio" "M8 — 🚀 MAREA lista para navegar" "P1" "autora del proyecto" "preparar el README y la presentación de portfolio" "comunicar con claridad el valor, alcance y arquitectura de MAREA" $'- El README identifica el producto, tagline, problema y solución propuesta.\n- Documenta arquitectura, stack, roadmap y estado real de implementación.\n- La presentación técnica explica decisiones y flujo funcional.\n- Ambos materiales reflejan MAREA como producto y portfolio con su contexto académico.'
create_issue "US-041 — Redactar y publicar el artículo de MAREA en Medium" "EP18" "Portfolio" "epic:portfolio" "M8 — 🚀 MAREA lista para navegar" "P0" "autora del proyecto" "redactar y publicar un artículo sobre MAREA en Medium" "compartir el proceso y resultado del proyecto" $'- El artículo explica el problema y la propuesta de valor.\n- Describe decisiones técnicas relevantes sin exponer secretos.\n- Incluye el estado real y los límites del proyecto.\n- El artículo se publica en Medium.'
create_issue "US-042 — Preparar y validar demo y presentación técnica final" "EP18" "Portfolio" "epic:portfolio" "M8 — 🚀 MAREA lista para navegar" "P0" "autora del proyecto" "preparar y validar la demo y presentación técnica final" "mostrar el flujo de MAREA de forma fiable" $'- La demo cubre el flujo disponible desde idea hasta revisión y salida.\n- La demo muestra contenido diferenciado por plataforma cuando esa capacidad esté implementada.\n- La presentación incluye arquitectura, stack, decisiones y trazabilidad.\n- Se verifica la demo en el entorno previsto antes de la entrega.'

echo "Resumen: creadas $created Issues; omitidas $skipped Issues."
